; Modules used by the bars in config.ini
include-file = $HOME/.config/bspwm/polybar/config/modules/battery.ini
include-file = $HOME/.config/bspwm/polybar/config/modules/bspwm.ini
include-file = $HOME/.config/bspwm/polybar/config/modules/backlight.ini
include-file = $HOME/.config/bspwm/polybar/config/modules/gap.ini
include-file = $HOME/.config/bspwm/polybar/config/modules/netspeed.ini
include-file = $HOME/.config/bspwm/polybar/config/modules/pulseaudio.ini
include-file = $HOME/.config/bspwm/polybar/config/modules/temperature.ini
