# Desktop-switch animation profile: SLIDE (macOS Mission Control style)
animation-for-prev-tag = "slide-out-center";
animation-for-next-tag = "slide-in-center";
enable-fading-prev-tag = true;
enable-fading-next-tag = true;
