#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Default cursor
xsetroot -cursor_name left_ptr

# Autostart programs
~/.config/bspwm/exec/autostart/autostart.sh

bspc monitor -d I II III IV V VI VII VIII IX X 
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_focus true

xrdb -merge ~/.Xresources &
