set -g fish_greeting ""

# pywal colour scheme (generated by wallpaper-set.sh; absent until first run).
if test -f ~/.cache/wal/colors.fish
    source ~/.cache/wal/colors.fish
end

# Toggle the picom desktop-switch animation (slide/fade) - macOS Mission-Control feel.
#   anim = switch-btw (needs ~/.local/bin on PATH, done by .xinitrc / .xprofile)
alias anim='switch-btw'